const ActionTypes = {
  //store actions
  SET_APPSNACKBAR_MESSAGE: "SET_APPSNACKBAR_MESSAGE",
  SET_AUTHORIZED: "SET_AUTHORIZED",
  SET_PROFILE: "SET_PROFILE",

  //saga actions
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  LOGOUT: "LOGOUT",
  CHECK_AUTHORIZED: "CHECK_AUTHORIZED",
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE"
};

export default ActionTypes;
